### ISSUE TITLE
Calling RS with no Context active

### ISSUE THREAD

**Issue by slott** [wasabeef/Blurry#103]
Regarding this change

https://github.com/wasabeef/Blurry/commit/631da3f3e824dac985010376e332f127d4f8d8fb#

I'm pretty sure this is causing a nasty crash that we are seeing.

This is only happening after upgrading from 3.0.0 to 4.0.0

We get a crash from another library "RealtimeBlurView" - with the following crash log

  android.renderscript.RSInvalidStateException: Calling RS with no Context active.
        at android.renderscript.RenderScript.validate(RenderScript.java:1255)
        at android.renderscript.Allocation.copyFrom(Allocation.java:992)
        at h.g.b.a.a.a(AndroidStockBlurImpl.java:66)
        at com.github.mmin18.widget.RealtimeBlurView.j(RealtimeBlurView.java:233)

Could it be that the change you made somehow interferes with this ?

If we revert to version 3.0.0 both libs happily co-exists.

**Comment by rtsketo** [comment]
I can confirm. Spent hours on this crash.
Although in my case it seems that there was a conflict with ShadowLayout (`net.orandja.shadowlayout:shadowlayout:1.0.1`).

**Comment by hexianqiao3755** [comment]
same question

**Comment by rtsketo** [comment]
Reverting to 3.0.0 seems the only solution so far for me.
I really like @wasabeef's libraries, but this hasn't been addressed in several moths and I find it appropriate (although awkward as well) to suggest an [alternative library](https://github.com/CameraKit/blurkit-android) I'm using. I hope I can help others devs by doing so and to bash this library.

**Comment by wasabeef** [comment]
@slott @hexianqiao3755 @rtsketo 

I'm sorry that I was late. Just released the revert version v4.0.1.

**Comment by hexianqiao3755** [comment]
@wasabeef  oh, that's great.
