### ISSUE TITLE
RuntimeException trying to use a recycled bitmap

### ISSUE THREAD

**Issue by GuilhE** [wasabeef/Blurry#116]
# Bug Reporting

> Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@1439588
>        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:66)
>        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:113)
>        at android.graphics.Canvas.drawBitmap(Canvas.java:1560)
>        at jp.wasabeef.blurry.Blur.of(Blur.java:62)
>        at jp.wasabeef.blurry.BlurTask$1$1.run(BlurTask.java:69)
>        at android.os.Handler.handleCallback(Handler.java:888)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at android.os.Looper.loop(Looper.java:213)
>        at android.app.ActivityThread.main(ActivityThread.java:8178)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
 

## Steps to Reproduce
Can't reproduce, I'm seeing this problem on Crashlytics reports

## OS details

- Device: Kimfly  A67, Xiaomi Redmi Note 9 Pro, HUAWEI P30 lite, HUAWEI Y6s, Galaxy Note8, Galaxy S8, Galaxy S7 edge, Galaxy A40, Galaxy A21s, Galaxy A20e.
- OS: Android 8-11

**Comment by cuiti** [comment]
I've started seeing this issue more and more frequently, without me changing anything that would explain the crash. 
Any ideas or workarounds to try?

**Comment by GuilhE** [comment]
No idea, still waiting for the author @wasabeef to reply.

**Comment by martinrehder** [comment]
still exists in 4.0.0
I'd like to think moving to 4.0.1 would solve it, but since I only see it in crashlytics, i have to release the app and let users run it before I can see if its fixed

**Comment by protoss5482** [comment]
Reproduce in adapter (Fast scrolling)
