### ISSUE TITLE
ERROR: android.support.v8.renderscript.RSRuntimeException: Error loading libRSSupport library

### ISSUE THREAD

**Issue by libern** [wasabeef/Blurry#16]
Hi, thanks for sharing such a nice library.

I have problem with this library (latest, from github) while running on Android 4.1.1, API 16, (Sony C1605).

How can I resolve this issue?

==================
Here is the debug output:

```
12-08 11:20:24.909 29458-29684/jp.wasabeef.example.blurry E/RenderScript_jni: No GC methods
12-08 11:20:24.919 29458-29684/jp.wasabeef.example.blurry V/RenderScript_jni: RS compat mode
12-08 11:20:24.939 29458-29458/jp.wasabeef.example.blurry D/Blurry: TIME 42ms
12-08 11:20:24.939 29458-29685/jp.wasabeef.example.blurry V/RenderScript_jni: RS compat mode
12-08 11:20:24.939 29458-29686/jp.wasabeef.example.blurry V/RenderScript_jni: RS compat mode
12-08 11:20:24.939 29458-29684/jp.wasabeef.example.blurry W/dalvikvm: threadid=11: thread exiting with uncaught exception (group=0x40c34498)
12-08 11:20:24.949 29458-29685/? W/dalvikvm: threadid=12: thread exiting with uncaught exception (group=0x40c34498)
12-08 11:20:24.949 29458-29684/? E/test: Exception
12-08 11:20:24.949 29458-29684/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                   android.support.v8.renderscript.RSRuntimeException: Error loading libRSSupport library
                                                       at android.support.v8.renderscript.RenderScript.internalCreate(RenderScript.java:1379)
                                                       at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1504)
                                                       at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1454)
                                                       at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1430)
                                                       at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1417)
                                                       at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:62)
                                                       at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java:60)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                       at java.lang.Thread.run(Thread.java:856)
```

**Comment by wasabeef** [comment]
@libern 

could you show me code :santa:

**Comment by libern** [comment]
@wasabeef The code is all yours, from the example project. While I run the example, it crashes with this error.

**Comment by kengura** [comment]
@libern  You can set BUILD_TOOLS_VERSION=21.1.1 in gradle.properties file to fix this issue.

**Comment by libern** [comment]
But I am targeting 23...

2015年12月14日星期一，Ruslan Krohalev <notifications@github.com> 写道：

> @libern <https://github.com/libern> You can set
> BUILD_TOOLS_VERSION=21.1.1 in gradle.properties file to fix this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wasabeef/Blurry/issues/16#issuecomment-164404490>.
>


-- 
Im Libern.

**Comment by wasabeef** [comment]
@kengura @libern 

Do you have this problems with 23.0.2?

**Comment by libern** [comment]
I still using 1.0.0, from 1.0.1 onwards to 1.0.5

All have issues loading library

2015年12月14日星期一，Daichi Furiya <notifications@github.com> 写道：

> @kengura <https://github.com/kengura> @libern <https://github.com/libern>
>
> Do you have this problems with 23.0.2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wasabeef/Blurry/issues/16#issuecomment-164418951>.
>


-- 
Im Libern.

**Comment by libern** [comment]
1.0.5 will show duplicate system support libarary, ***.so

2015年12月14日星期一，Daichi Furiya <notifications@github.com> 写道：

> @kengura <https://github.com/kengura> @libern <https://github.com/libern>
>
> Do you have this problems with 23.0.2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wasabeef/Blurry/issues/16#issuecomment-164418951>.
>


-- 
Im Libern.

**Comment by kengura** [comment]
@libern I am targeting 23 api with 21 build tools. It seems to work.
@wasabeef Yes i have the same problem with 23.0.2 on Lenovo P780 (Android 4.2.1). Other devices work well.

**Comment by AndroidLTG** [comment]
metoo. same problem :(

**Comment by Pkmmte** [comment]
I'm having the same issue. According to Crashlytics, the problem lies with the following code:
RenderScript rs = RenderScript.create(context);

It may be a RenderScript issue but perhaps you could try/catch it and allow us to provide a callback to handle such errors.

**Comment by wasabeef** [comment]
@xiadeye 

Hi.
try. Blurry `2.0.0`
