### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by TonyHaddad91** [wasabeef/Blurry#28]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 5529612 byte allocation with 2175304 free bytes and 2MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
       at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:51)
       at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java:60)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

Any help for this ?
Thanks

**Comment by titooan** [comment]
I had the same problem. Does someone has an idea of how to solve it? 

Thanks

**Comment by moshosseini** [comment]
I had the same problem and I solved it by adding android:largeHeap="true" to app manifest. I know this is not a good solution but it can solve your problem

**Comment by revg75** [comment]
Having same problem, looks like a memory leak. Will reply if I find a proper solution.
