### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by TonyHaddad91** [wasabeef/Blurry#29]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1302)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1358)
       at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:60)
       at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java:60)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Ariel4Android** [comment]
The same issue happened on some 3rd customized Android OS within my depolyed app.
I tried to modify code BlurTask.java, frome line 60 like this

`  Context context = contextWeakRef.get();
        if (context != null) {

          final BitmapDrawable bitmapDrawable =
                  new BitmapDrawable(res, Blur.of(context, capture, factor));

          if (callback != null) {
            new Handler(Looper.getMainLooper()).post(new Runnable() {
              @Override public void run() {
                callback.done(bitmapDrawable);
              }
            });
          }
        }`
