### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by yanglichuan** [wasabeef/Blurry#35]
e: FATAL EXCEPTION: pool-10-thread-1
                                                                    Process: com.ks.kaishustory, PID: 23125
                                                                    java.lang.OutOfMemoryError
                                                                        at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
                                                                        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:686)
                                                                        at jp.wasabeef.blurry.internal.Blur.of(Blur.java:78)
                                                                        at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java:61)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)

**Comment by hoangtu23** [comment]
I have the same issue here:

java.lang.OutOfMemoryError
                                                                            at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
                                                                            at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:686)
                                                                            at jp.wasabeef.blurry.internal.Blur.of(Blur.java:78)
                                                                            at jp.wasabeef.blurry.internal.Blur.of(Blur.java:41)
                                                                            at jp.wasabeef.blurry.Blurry$ImageComposer.into(Blurry.java:163)

**Comment by engineers-bojan** [comment]
Same...happens mostly on high end phones like samsung S7 and edge7.

**Comment by maxim-yudin** [comment]
The same problem

at android.renderscript.RenderScript.destroy(RenderScript.java:1308)
at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:102)
at jp.wasabeef.blurry.internal.Blur.of(Blur.java:67)

**Comment by IlanVokov** [comment]
same problem seems like created bitmaps not deleted or recyled

**Comment by moshosseini** [comment]
I have this problem and solved this by adding android:largeHeap="true" to app manifest. I know this is not a good solution but it can solve your problem.
