### ISSUE TITLE
Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()

### ISSUE THREAD

**Issue by TonyHaddad91** [wasabeef/Blurry#4]
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1224)
            at android.graphics.Canvas.drawBitmap(Canvas.java:1280)
            at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:52)
            at jp.wasabeef.blurry.Blurry$ImageComposer.into(Blurry.java:153)

**Comment by Pkmmte** [comment]
I had the same issue when I tried to apply a blur onto an ImageView right after the views were created. I solved it by making sure the blur was applied only after the views were ready like so:

imageView.post(new Runnable() {
    @Override
    public void run() {
        // Try blurring here
    }
});

**Comment by Isabellle** [comment]
Doesn't work for me using the runnable, getting "Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()'"

**Comment by AlexeyGodyaev** [comment]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1300)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1356)
       at jp.wasabeef.blurry.internal.Blur.of(Blur.java:63)
       at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java:70)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
samsung SM-G935F 6.0.1
