### ISSUE TITLE
Crash using adapters

### ISSUE THREAD

**Issue by cbedoy** [wasabeef/Blurry#46]
Hi!

I had a crash while using adapters

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
                                                                at jp.wasabeef.blurry.internal.Blur.of(Blur.java:42)
                                                                at jp.wasabeef.blurry.Blurry$ImageComposer.into(Blurry.java:163)
                                                                at org.parley.models.common.base.BaseViewCell.onBindViewHolder(BaseViewCell.java:487)

I don't know if you are calling recycler() while reload data

**Comment by uburoiubu** [comment]
Same for me.

**Comment by parsam10** [comment]
same for me
