### ISSUE TITLE
async() throws RuntimeException

### ISSUE THREAD

**Issue by tuhin10** [wasabeef/Blurry#5]
I am using the below code for blurring which is working fine for me. 

        Blurry.with(MainActivity.this)
                            .radius(25)
                            .sampling(2)
                            .onto((ViewGroup) findViewById(R.id.content));

but if I use the Async mode it throws RuntimeException

   Blurry.with(MainActivity.this)
                            .radius(25)
                            .sampling(2)
                            .async()
                            .animate(500)
                            .onto((ViewGroup) findViewById(R.id.content));

**Comment by wasabeef** [comment]
Hi.
show me stack trace.

**Comment by tuhin10** [comment]
fatal error : An error occured while executing doInBackground()
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6254)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:902)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4637)
at android.view.View.invalidateInternal(View.java:11690)
at android.view.View.invalidate(View.java:11654)
at android.view.View.invalidate(View.java:11638)
at com.packgname.test.PWheel.onDraw(PWheel.java:272)
at android.view.View.draw(View.java:15114)
at android.view.View.draw(View.java:15022)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15117)
08-19 22:31:04.008: E/ACRA(19759): 	at android.widget.FrameLayout.draw(FrameLayout.java:592)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15022)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15117)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15022)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15017)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
08-19 22:31:04.008: E/ACRA(19759): 	at android.widget.ListView.drawChild(ListView.java:3396)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
08-19 22:31:04.008: E/ACRA(19759): 	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2596)
08-19 22:31:04.008: E/ACRA(19759): 	at android.widget.ListView.dispatchDraw(ListView.java:3391)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15117)
08-19 22:31:04.008: E/ACRA(19759): 	at android.widget.AbsListView.draw(AbsListView.java:4085)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15022)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15117)
08-19 22:31:04.008: E/ACRA(19759): 	at com.packgname.test.SwipeRefreshLayoutLinear.draw(SwipeRefreshLayoutLinear.java:244)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15022)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.draw(View.java:15117)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.buildDrawingCache(View.java:14343)
08-19 22:31:04.008: E/ACRA(19759): 	at android.view.View.buildDrawingCache(View.java:14187)
08-19 22:31:04.008: E/ACRA(19759): 	at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:50)
08-19 22:31:04.008: E/ACRA(19759): 	at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:58)
08-19 22:31:04.008: E/ACRA(19759): 	at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:1)
08-19 22:31:04.008: E/ACRA(19759): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-19 22:31:04.008: E/ACRA(19759): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-19 22:31:04.008: E/ACRA(19759): 	... 4 more

**Comment by tuhin10** [comment]
This is how I am using it

Blurry.with(mActivity)    	
    	.radius(25)
        .sampling(4)
    	.capture(mContainer).into(mBlurImage);

**Comment by tuhin10** [comment]
Any update on this?

**Comment by wasabeef** [comment]
@tuhin10 
Let me think about it.

**Comment by maxandron** [comment]
The problem with this is not Blurry I believe but the fact you are trying to modify your view from an async task.
Use blurry in the onpostexecute() method not in doinbackground() like you do here.

**Comment by wasabeef** [comment]
@tuhin10 @maxandron 

Try this Version `compile 'jp.wasabeef:blurry:1.0.1'`

**Comment by wasabeef** [comment]
https://github.com/wasabeef/Blurry/commit/1894d3c9dad3593b4277ca9a7c2d0b2276eb866d

**Comment by tuhin10** [comment]
@wasabeef thanx. will test it and let you know.

**Comment by tuhin10** [comment]
08-28 00:48:20.671: E/ACRA(28621): java.lang.RuntimeException: An error occured while executing doInBackground()
08-28 00:48:20.671: E/ACRA(28621): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
08-28 00:48:20.671: E/ACRA(28621): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
08-28 00:48:20.671: E/ACRA(28621): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
08-28 00:48:20.671: E/ACRA(28621): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
08-28 00:48:20.671: E/ACRA(28621): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-28 00:48:20.671: E/ACRA(28621): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-28 00:48:20.671: E/ACRA(28621): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-28 00:48:20.671: E/ACRA(28621): 	at java.lang.Thread.run(Thread.java:818)
08-28 00:48:20.671: E/ACRA(28621): Caused by: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e0d1c9a
08-28 00:48:20.671: E/ACRA(28621): 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
08-28 00:48:20.671: E/ACRA(28621): 	at android.graphics.Canvas.drawBitmap(Canvas.java:1280)
08-28 00:48:20.671: E/ACRA(28621): 	at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:59)
08-28 00:48:20.671: E/ACRA(28621): 	at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:66)
08-28 00:48:20.671: E/ACRA(28621): 	at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:1)
08-28 00:48:20.671: E/ACRA(28621): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-28 00:48:20.671: E/ACRA(28621): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by tuhin10** [comment]
now getting this exception with jp.wasabeef:blurry:1.0.1

**Comment by wasabeef** [comment]
@tuhin10 

oops...
whats the android version?

**Comment by tuhin10** [comment]
Android Version-5.0.2 Cyanogen Os 12.0

**Comment by wasabeef** [comment]
@tuhin10 
OK. Thanks.

i willl fix 1.0.2.

**Comment by tuhin10** [comment]
ok thank you

**Comment by wasabeef** [comment]
@tuhin10 

Released the v1.0.2

**Comment by maxandron** [comment]
Thank you! just as I started having the same issue. The latest version seems to work for me

**Comment by wasabeef** [comment]
@maxandron 

thank you.

**Comment by maxandron** [comment]
Hi,
I myself can not replicate the issue, but I get the following (not consistent) crash report from some users:
```java
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@24aced1b
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java)
       at android.graphics.Canvas.drawBitmap(Canvas.java)
       at jp.wasabeef.blurry.internal.Blur.rs(Blur.java)
       at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
       at java.lang.Thread.run(Thread.java)
```

This happens with the latest version (1.0.4)

I know it probably will not help, since I don't believe it has something to do with my usage, but here is the code using the library:
```java
Glide.with(this)
        .load(url)
        .into(new GlideDrawableImageViewTarget(mBlurredProfile) {
            @Override
            public void onResourceReady(GlideDrawable resource, GlideAnimation<? super
                    GlideDrawable> animation) {
                super.onResourceReady(resource, animation);
                Blurry.with(BaseActivity.this)
                        .async()
                        .capture(mBlurredProfile)
                        .into(mBlurredProfile);
            }
        });
```

**Comment by wasabeef** [comment]
@maxandron 

This it?
https://github.com/wasabeef/glide-transformations

**Comment by maxandron** [comment]
I did not know about this library, I will try it. Thanks

**Comment by azizbekian** [comment]
This issues is not resolved. Running on 5.1.1 CyanogenMod, Asus Zenfone 2

**Comment by fidschau** [comment]
I am also getting it on 6.0.1, Samsung SM-G900F.
`Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@77fd9c
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1301)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1356)
       at jp.wasabeef.blurry.internal.Blur.of(Blur.java:63)
       at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java:70)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#0. Crashed: pool-9-thread-4: 0 0 0x0000000000000000
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1301)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1356)
       at jp.wasabeef.blurry.internal.Blur.of(Blur.java:63)
       at jp.wasabeef.blurry.internal.BlurTask$1.run(BlurTask.java:70)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#1. Thread-2409
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

#2. Thread-2426
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
`
