### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zhoufu24** [wasabeef/Blurry#6]
java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
            at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1224)
            at android.graphics.Canvas.drawBitmap(Canvas.java:1280)
            at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:52)
            at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:58)
            at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:27)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by wasabeef** [comment]
tha's the same.
https://github.com/wasabeef/Blurry/issues/5
